### ISSUE TITLE
关于 Response 接口？

### ISSUE THREAD

**Issue by BeanWei** [karldoenitz/Tigo#1]
RT, 小白有个疑问，为什么 Response 类型不直接定义一个空接口，感觉现在这种写起来有点拖沓。还是我写法有问题？
```Go
helloHandler.ResponseAsJson(struct {
	TigoWeb.Response
	Status string `json:"status"`
}{Status: "ok"})
```
另外 还有两点建议：
- 例子中可以添加 ResponseAsJson 的实列吗？
- 示例中的 IP 建议还是设置为 127.0.0.1 吧，设置 0.0.0.0 有点坑0.0

**Comment by karldoenitz** [comment]
@BeanWei ，好的，demo如下：
`package main

import (
	"github.com/karldoenitz/Tigo/TigoWeb"
)

type JsonBase struct {
	TigoWeb.BaseResponse
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (JsonBase)Print()  {
}

type HelloJson struct {
	TigoWeb.BaseHandler
}

func (helloJson *HelloJson)Get() {
	response := JsonBase{
		Name: "Tigo",
		Version: "v1.0.0",
	}
	helloJson.ResponseAsJson(response)
}

var urls = map[string] interface {} {
	"/test-json": &HelloJson{},
}

func main() {
	application := TigoWeb.Application{
		IPAddress:  "127.0.0.1",
		Port:       8888,
		UrlPattern: urls,
	}
	application.Run()
}
`
response的结构体必须实现一个Print方法，这个要求将会在后期去掉，后续版本会改良的。
实例中的IP会在后续一同改正。

**Comment by karldoenitz** [comment]
已更新
