### ISSUE TITLE
文档跳转错误

### ISSUE THREAD

**Issue by FridayOK** [karldoenitz/Tigo#10]
【问题描述】
文档跳转错误，不能跳转到指定位置。
【操作步骤】
例如：
![image](https://user-images.githubusercontent.com/44257488/51731758-ee8f0d80-20b6-11e9-8afa-77e9a0c51c3f.png)
跳转结果：
![image](https://user-images.githubusercontent.com/44257488/51731792-08305500-20b7-11e9-8296-b4265d2406ff.png)

【问题分析】
锚链接异常，应该使用markdown自支持的结构，不能使用html的锚链接方式。

**Comment by karldoenitz** [comment]
锚链接问题将在bugfix分支中修复，修复后合并至master分支。

**Comment by Natalia2pretty** [comment]
🙂
