### ISSUE TITLE
出现500错误时连接中断，并没有响应客户端

### ISSUE THREAD

**Issue by FridayOK** [karldoenitz/Tigo#13]
- go version: 1.x
- Tigo version (or commit ref): 1.0.3
- operating system: Windows Linux Mac都有这个问题

## Description
【问题描述】服务运行时出现错误，无论什么错误，直接服务就中断了，没有给客户端任何响应。
## Operation
【操作步骤】在Handler中panic一下就可以复现。
## Analysis(optional)
【问题分析】框架的中间层代码并没有对错误异常进行recover处理。

**Comment by karldoenitz** [comment]
收到，将在最新版本中处理。

**Comment by karldoenitz** [comment]
之前对于运行时错误没有进行recover处理，连接直接就中断了，增加一个处理错误的中间件即可。

**Comment by Goosense** [comment]
@karldoenitz 有了 #11 ，是不是跟这个功能重复了？

**Comment by Goosense** [comment]
@FridayOK 这个问题是否可以通过 #11 来解决？

**Comment by karldoenitz** [comment]
@Goosense ，这个处理主要是为了处理运行时错误，而 #11 是用来处理开发者自定义错误的。

**Comment by hotflask** [comment]
当出现运行时错误的时候，应该判断当前环境，debug环境下应该提示具体错误，生产环境下就不用提示了。
