### ISSUE TITLE
接口访问时log级别问题

### ISSUE THREAD

**Issue by FridayOK** [karldoenitz/Tigo#15]
## Info
- go version: all
- Tigo version (or commit ref): all
- operating system: all

## Description
【问题描述】
访问接口时打印的log，级别都是trace级别，不严谨，trace一般是跟进问题时使用此级别。
## Operation
【操作步骤】
随机访问一个接口查看log即可。
## Analysis(optional)
【问题分析】
Trace级别是跟进排查，普通的log打印使用info就可以。

**Comment by HuangHuiFen** [comment]
我也觉得这个log打印的乱七八糟的，也没有状态码，500的时候log级别不应该是Error吗？正常情况下log不应该是info吗？都弄个trace是什么意思？完事还不打印http状态码。
