### ISSUE TITLE
CheckFormBinding错误

### ISSUE THREAD

**Issue by ssundabao** [karldoenitz/Tigo#18]
- go version: all
- Tigo version (or commit ref): all
- operating system: all

## Description
【问题描述】使用CheckFormBinding和CheckParamBinding都不能检验form的合法性
## Operation
【操作步骤】直接post请求，就会复现
## Analysis(optional)
【问题分析】binding.UnmarshalForm有bug，测试用例没有覆盖这个函数，修复这个函数即可。

**Comment by karldoenitz** [comment]
bug无效，此问题不存在，若能复现请提供具体代码及相应http报文。
