### ISSUE TITLE
如何在代码层级进行日志及静态文件路径配置

### ISSUE THREAD

**Issue by GamerSkyJu** [karldoenitz/Tigo#21]
如何在代码层级进行日志及静态文件路径配置，从文档中只找到了通过配置文件配置的方式，有些应用场景下我必须在代码中配置，请问怎么弄。

**Comment by karldoenitz** [comment]
目前没有代码级别配置，只能通过配置文件。

**Comment by karldoenitz** [comment]
增加`InitGlobalConfigWithObj`函数，通过代码层级可以初始化全局配置。
