### ISSUE TITLE
request模块无法发送xml格式的报文

### ISSUE THREAD

**Issue by YoshiniMashimi** [karldoenitz/Tigo#22]
# request.{{ Method }}功能完善建议
这些http请求方式都没有对xml格式的支持，但是很多地方还是用得到xml，能加上吗？
如果不能，最好加一个发送`[]byte`数据的请求方式，需要发送的报文体我们自己写，总比无法发送好，有功能还是希望完善的，不要放一下不完善的功能出来，用了都不和谐。

**Comment by karldoenitz** [comment]
这是一个很好的问题，已加入1.0.8版本处理。
