### ISSUE TITLE
tiger工具不能更新项目

### ISSUE THREAD

**Issue by QinJiaQing** [karldoenitz/Tigo#30]
- With issues:
  - Use the search tool before opening a new issue.
  - Please provide source code and commit sha if you found a bug.
  - Review existing issues and provide feedback or react to them.

- go version: 1.9
- Tigo version (or commit ref):1.0.7
- operating system:Windows8

## Description
\[description]  
【问题描述】tiger update更新框架不成功
## Operation
\[operation]  
【操作步骤】直接直行update命令

**Comment by karldoenitz** [comment]
update命令当前支持的go版本>=1.11

**Comment by flusket** [comment]
win需要`set GO111MODULE=on`，其他的需要`export GO111MODULE=on`
