### ISSUE TITLE
多线程输出异常

### ISSUE THREAD

**Issue by karldoenitz** [karldoenitz/Tigo#32]
- go version: all
- Tigo version (or commit ref): all
- operating system: all

## Description
\[description]  
【问题描述】客户端开多进程或多线程，请求服务端，返回数据紊乱
## Operation
\[operation]  
【操作步骤】随便找一种编程语言，多线程3000个请求
## Analysis(optional)
\[analysis]  
【问题分析】连接公用一个对象，没有重新实例化responsewriter造成的

**Comment by forkdan** [comment]
这个问题有可能是多个httpresponsewriter用了同一块内存，多协程读写容易出现数据混写的现象。

**Comment by kruscarary** [comment]
这个bug我也遇见了，求解决

**Comment by karldoenitz** [comment]
1.1.1中紧急修复了一版，1.1.2版本中会进行优化处理。

**Comment by pangzi3** [comment]
> 这个问题有可能是多个httpresponsewriter用了同一块内存，多协程读写容易出现数据混写的现象。

这个是HTTPresponsewriter公用一块内存导致的，http响应数据都写到了一块内存里，肯定有问题。
@karldoenitz @kruscarary

**Comment by xuyongwei1** [comment]
这个bug很坑啊，多亏有个临时补救的办法，要不就被坑死了。好在版本1.1.1中解决了。
