### ISSUE TITLE
怎么上传下载文件？

### ISSUE THREAD

**Issue by heightfar** [karldoenitz/Tigo#33]
rt
怎么弄？有api接口吗？

**Comment by karldoenitz** [comment]
- 下载文件可以参考api[点击此处](https://github.com/karldoenitz/Tigo/blob/master/documentation/documentation.md#func-application-applicationmountfileserver)，挂载网络文件系统；
- 上传请关注[此处](https://github.com/karldoenitz/Tigo/issues/31)
