### ISSUE TITLE
API优化建议

### ISSUE THREAD

**Issue by LinZhai** [karldoenitz/Tigo#39]
* 建议增加两个重定向的API，分别对应http状态码`307`和`308`;
【问题描述】
* 目前的`BaseHandler.Redirect`和`BaseHandler.RedirectPermanently`都会使浏览器默认采用Get请求方式，但根据[RFC7231](https://tools.ietf.org/html/rfc7231)的标准，当使用`307`、`308`两种状态码时，不允许重定向时发生请求方式变化。

**Comment by karldoenitz** [comment]
1.3.0分支已经创建，代码可以提交到1.3.0
