### ISSUE TITLE
不能安装

### ISSUE THREAD

**Issue by toolyq** [karldoenitz/Tigo#52]
>go get github.com/karldoenitz/Tigo/...
go: warning: "github.com/karldoenitz/Tigo/..." matched no packages

**Comment by karldoenitz** [comment]
可以试一下`go get -u github.com/karldoenitz/Tigo/...`

**Comment by LPDSB** [comment]
@toolyq 跟golang版本有关吧？你用的哪个版本的？

**Comment by toolyq** [comment]
> @toolyq 跟golang版本有关吧？你用的哪个版本的？

go version go1.13.4 windows/amd64
